#include "default.inc"

camera{
    location <0,0.1,0.01152>
    angle 30
    look_at <0,0,0.01152>
    sky <-1,0,0>
    right x*image_width/image_height
}
light_source{
    <0,2500,10>
    color White
}

sphere_sweep {
    linear_spline 145
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<0.00023327463679397015,0.00013792557436943315,0.022881103448275864>,nan
    texture{
        pigment{ color rgb<31/255,119/255,180/255> transmit 0.500000 }
        finish{ phong 1 }
    }
    }

sphere_sweep {
    linear_spline 145
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<-0.00023608436964978483,0.00013305897433726164,0.022881103448273106>,nan
    texture{
        pigment{ color rgb<255/255,127/255,14/255> transmit 0.500000 }
        finish{ phong 1 }
    }
    }

sphere_sweep {
    linear_spline 145
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<2.8097328300064796e-06,-0.00027098454872201,0.022881103448278622>,nan
    texture{
        pigment{ color rgb<44/255,160/255,44/255> transmit 0.500000 }
        finish{ phong 1 }
    }
    }
