#include "default.inc"

camera{
    location <0,0.1,0.01152>
    angle 30
    look_at <0,0,0.01152>
    sky <-1,0,0>
    right x*image_width/image_height
}
light_source{
    <0,2500,10>
    color White
}

sphere_sweep {
    linear_spline 145
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<0.00022301103967800284,0.0001539702150690082,0.022881103448275864>,nan
    texture{
        pigment{ color rgb<31/255,119/255,180/255> transmit 0.500000 }
        finish{ phong 1 }
    }
    }

sphere_sweep {
    linear_spline 145
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<-0.0002448476375321712,0.00011614811814962279,0.022881103448273106>,nan
    texture{
        pigment{ color rgb<255/255,127/255,14/255> transmit 0.500000 }
        finish{ phong 1 }
    }
    }

sphere_sweep {
    linear_spline 145
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<2.1836597829499784e-05,-0.000270118333235722,0.022881103448278622>,nan
    texture{
        pigment{ color rgb<44/255,160/255,44/255> transmit 0.500000 }
        finish{ phong 1 }
    }
    }
