#include "default.inc"

camera{
    location <0,0.1,0.01152>
    angle 30
    look_at <0,0,0.01152>
    sky <-1,0,0>
    right x*image_width/image_height
}
light_source{
    <0,2500,10>
    color White
}

sphere_sweep {
    linear_spline 145
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<0.00021664804923098922,0.00016280206906742304,0.022881103448275864>,nan
    texture{
        pigment{ color rgb<31/255,119/255,180/255> transmit 0.500000 }
        finish{ phong 1 }
    }
    }

sphere_sweep {
    linear_spline 145
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<-0.0002493147522337353,0.00010622167977857342,0.022881103448273106>,nan
    texture{
        pigment{ color rgb<255/255,127/255,14/255> transmit 0.500000 }
        finish{ phong 1 }
    }
    }

sphere_sweep {
    linear_spline 145
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<nan,nan,nan>,nan
    ,<3.266670297878346e-05,-0.0002690237488640673,0.022881103448278622>,nan
    texture{
        pigment{ color rgb<44/255,160/255,44/255> transmit 0.500000 }
        finish{ phong 1 }
    }
    }
