name: elasticapp (Elastica++ based backend) tests

# trigger run only on changes to the backend folder.
on:
  push:
    paths:
      - backend/**
  pull_request:
    paths:
      - backend/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11"] #, "3.12"]
        os: [ubuntu-latest] # , macos-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          uv-version: latest
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make install-dev-deps PYTHON_VERSION=${{ matrix.python-version }}
          uv cache prune --ci
          source .venv/bin/activate

      - name: Install PyElastica + backend
        run: |
          uv pip install . -v
          uv pip install ./backend -v
      - name: Run elasticapp tests
        run: |
          cd backend
          make test
